version: '3'

services:

  postgresql:
    image: docker.io/bitnami/postgresql:15.1.0
    environment:
      - POSTGRESQL_USERNAME=keycloak
      - POSTGRESQL_PASSWORD=keycloak
      - POSTGRESQL_DATABASE=keycloak
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    ports:
      - "5432:5432"

  keycloak:
    image: docker.io/bitnami/keycloak:20.0.2
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_DATABASE_HOST=postgresql
      - KEYCLOAK_DATABASE_PORT=5432
      - KEYCLOAK_DATABASE_NAME=keycloak
      - KEYCLOAK_DATABASE_USER=keycloak
      - KEYCLOAK_DATABASE_PASSWORD=keycloak

      - KEYCLOAK_ADMIN_USER=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    depends_on:
      - postgresql

volumes:
  postgresql_data:
    driver: local
