version: '3'

name: dotnet-api-with-keycloak

services:

  postgresql:
    container_name: postgresql
    image: docker.io/bitnami/postgresql:15.1.0
    environment:
      - POSTGRESQL_USERNAME=keycloak
      - POSTGRESQL_PASSWORD=keycloak
      - POSTGRESQL_DATABASE=keycloak
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    ports:
      - "5432:5432"

  keycloak:
    container_name: keycloak
    image: docker.io/bitnami/keycloak:20.0.2
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_DATABASE_HOST=postgresql
      - KEYCLOAK_DATABASE_PORT=5432
      - KEYCLOAK_DATABASE_NAME=keycloak
      - KEYCLOAK_DATABASE_USER=keycloak
      - KEYCLOAK_DATABASE_PASSWORD=keycloak

      - KEYCLOAK_ADMIN_USER=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin

    # command: ['./kc.sh', 'import', '--file', '/tmp/realm-export.json']
    volumes:
      - ./imports/realm-export.json:/tmp/realm-export.json
    depends_on:
      - postgresql

  api:
    container_name: api
    build:
        context: ../src/
        no_cache: true
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - "5259:80"

volumes:
  postgresql_data:
    driver: local
